### ISSUE TITLE
ROS catkin_make

### ISSUE THREAD

**Issue by JulienRineau** [robotology/osqp-eigen#129]
Hi I'm trying to make [this](https://github.com/ShuoYangRobotics/A1-QP-MPC-Controller) repo work without docker.
But even after installing osqp-eigen (from source and with conda) I obtain this error:
```
In file included from /usr/include/OsqpEigen/OsqpEigen.h:10,
                 from /home/parallels/capstone/workspace/src/a1_cpp/src/test/test_rotation.cpp:8:
/usr/include/OsqpEigen/Constants.hpp:12:10: fatal error: osqp.h: No such file or directory
   12 | #include <osqp.h>
      |          ^~~~~~~~
compilation terminated.
make[2]: *** [a1_cpp/CMakeFiles/test_rotation.dir/build.make:63: a1_cpp/CMakeFiles/test_rotation.dir/src/test/test_rotation.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2868: a1_cpp/CMakeFiles/test_rotation.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
Invoking "make -j4 -l4" failed
```
Does someone have an idea on how to solve this ?

**Comment by S-Dafarra** [comment]
Hi @JulienRineau, thanks for the issue.

Could you please post here the steps you are following. That could give us a possibility to reproduce the issue.

**Comment by JulienRineau** [comment]
Thank you @S-Dafarra. Here is what I have done:

1. [Create a ros workspace](https://wiki.ros.org/catkin/Tutorials/create_a_workspace) and copy past the [a1_cpp](https://github.com/ShuoYangRobotics/A1-QP-MPC-Controller/tree/main/src/a1_cpp) package in src
2. Try with conda: `conda install -c conda-forge osqp-eigen`
3. Try to build my ros workspace with `catkin_make` but obtain the above error
4. Try to install osqp-eigen from source: `git clone https://github.com/robotology/osqp-eigen.git` in the folder containing my ros workspace
6. `cd osqp-eigen`
7. `mkdir build`
8. `cd build`
9. `cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ../ ` (I'm not sure of this part)
10. `make`
11. `sudo make install`
12. `OsqpEigen_DIR=/path/to/osqp-eigen/ ` ('m not sure of this part)
13. Obtain the above error

I'm using ros Noetic with Ubuntu 20.04

**Comment by traversaro** [comment]
Hello @JulienRineau, how did you installed the ROS installation with which you created the ROS workspace? If you did it with apt (the default and official installation method), then in general you can't install and use conda(-forge) packages. apt and conda effectively are completly separated distributions of C++ libraries, that even have different `libstdc++` version, so you **can't mix** them.
Furthermore, **never install in `/usr`**, that location is reserved for apt package. To recover your system I suggest to:

A. Make sure that you do not have any conda environment active when you work with ROS/apt, ensuring that you are not activating any in the `.bashrc` or similar, and that even your base environment is not active (i.e. call `conda config --set auto_activate_base true` once). This should revert any problem introduced by step 2.
B. Uninstall the `osqp-eigen` that you installed in `/usr`, by going in the build dir and running `sudo make uninstall . This should revert any problem introduced by step 8.

At this point, I think you can start again, probably installing osqp-eigen by source either in a user directory. From the problem you have, probably it is important to check:
* the `CMakeLists.txt` of your project, to ensure that it is correctly linking `OsqpEigen::OsqpEigen`
* double check how you installed osqp

**Comment by traversaro** [comment]
By the way, now that I think of @wxmerkt in https://github.com/robotology/osqp-eigen/pull/109 added a `package.xml` in osqp-eigen for catkin compatibility, so perhaps if he has time he may have some hints on how to compile and install osqp-eigen directly via catkin (thanks in advance, my experience with ROS build tools is mostly limited to colcon).

**Comment by wxmerkt** [comment]
You can directly compile OSQP and osqp-eigen in a catkin workspace. To do so, clone OSQP from https://github.com/ori-drs/osqp (the only modifcation being an added package.xml) and osqp-eigen from this repository - directly into your catkin_ws/src. You can then compile with `catkin build` or `catkin_make_isolated` - but not `catkin_make`. I did not have to modify any environment variables but I am noticing a transitive dependency issue when including constants - it appears that the `osqp::osqp` target that is linked to `OsqpEigen::OsqpEigen` does not get searched/its `INTERFACE_INCLUDE_DIRECTORIES` appended?

**Comment by traversaro** [comment]
Thanks a lot @wxmerkt !

**Comment by JulienRineau** [comment]
Thanks @wxmerkt and @traversaro for your help.
Running `catkin_make` give me now another error. Have you ever encountered this ?
```
parallels@ubuntu-linux-20-04-desktop:~/capstone/workspace$ catkin_make_isolated
Base path: /home/parallels/capstone/workspace
Source space: /home/parallels/capstone/workspace/src
Build space: /home/parallels/capstone/workspace/build_isolated
Devel space: /home/parallels/capstone/workspace/devel_isolated
Install space: /home/parallels/capstone/workspace/install_isolated
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~  traversing 13 packages in topological order:
~~  - a1_description
~~  - aliengo_description
~~  - b1_description
~~  - go1_description
~~  - laikago_description
~~  - osqp (plain cmake)
~~  - osqp-eigen (plain cmake)
~~  - unitree_legged_msgs
~~  - a1_cpp
~~  - unitree_controller
~~  - unitree_gazebo
~~  - unitree_legged_control
~~  - unitree_legged_real
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

==> Processing catkin package: 'a1_description'
Makefile exists, skipping explicit cmake invocation...
==> make cmake_check_build_system in '/home/parallels/capstone/workspace/build_isolated/a1_description'
==> make -j4 -l4 in '/home/parallels/capstone/workspace/build_isolated/a1_description'
<== Finished processing package [1 of 13]: 'a1_description'

==> Processing catkin package: 'aliengo_description'
==> Building with env: '/home/parallels/capstone/workspace/devel_isolated/a1_description/env.sh'
Makefile exists, skipping explicit cmake invocation...
==> make cmake_check_build_system in '/home/parallels/capstone/workspace/build_isolated/aliengo_description'
==> make -j4 -l4 in '/home/parallels/capstone/workspace/build_isolated/aliengo_description'
<== Finished processing package [2 of 13]: 'aliengo_description'

==> Processing catkin package: 'b1_description'
==> Building with env: '/home/parallels/capstone/workspace/devel_isolated/aliengo_description/env.sh'
Makefile exists, skipping explicit cmake invocation...
==> make cmake_check_build_system in '/home/parallels/capstone/workspace/build_isolated/b1_description'
==> make -j4 -l4 in '/home/parallels/capstone/workspace/build_isolated/b1_description'
<== Finished processing package [3 of 13]: 'b1_description'

==> Processing catkin package: 'go1_description'
==> Building with env: '/home/parallels/capstone/workspace/devel_isolated/b1_description/env.sh'
Makefile exists, skipping explicit cmake invocation...
==> make cmake_check_build_system in '/home/parallels/capstone/workspace/build_isolated/go1_description'
==> make -j4 -l4 in '/home/parallels/capstone/workspace/build_isolated/go1_description'
<== Finished processing package [4 of 13]: 'go1_description'

==> Processing catkin package: 'laikago_description'
==> Building with env: '/home/parallels/capstone/workspace/devel_isolated/go1_description/env.sh'
Makefile exists, skipping explicit cmake invocation...
==> make cmake_check_build_system in '/home/parallels/capstone/workspace/build_isolated/laikago_description'
==> make -j4 -l4 in '/home/parallels/capstone/workspace/build_isolated/laikago_description'
<== Finished processing package [5 of 13]: 'laikago_description'

==> Processing plain cmake package: 'osqp'
==> Building with env: '/home/parallels/capstone/workspace/devel_isolated/laikago_description/env.sh'
==> cmake /home/parallels/capstone/workspace/src/osqp -DCMAKE_INSTALL_PREFIX=/home/parallels/capstone/workspace/devel_isolated/osqp -G Unix Makefiles in '/home/parallels/capstone/workspace/build_isolated/osqp/devel'
-- We are on a Linux system
-- Embedded is OFF
-- Printing is ON
-- Profiling is ON
-- User interrupt is ON
-- Floats are OFF
-- Long integers (64bit) are ON
-- Code coverage is OFF
-- MKL Pardiso: ON
CMake Error at lin_sys/direct/qdldl/CMakeLists.txt:2 (add_subdirectory):
  The source directory

    /home/parallels/capstone/workspace/src/osqp/lin_sys/direct/qdldl/qdldl_sources

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
See also "/home/parallels/capstone/workspace/build_isolated/osqp/devel/CMakeFiles/CMakeOutput.log".
<== Failed to process package 'osqp': 
  Command '['/home/parallels/capstone/workspace/devel_isolated/laikago_description/env.sh', 'cmake', '/home/parallels/capstone/workspace/src/osqp', '-DCMAKE_INSTALL_PREFIX=/home/parallels/capstone/workspace/devel_isolated/osqp', '-G', 'Unix Makefiles']' returned non-zero exit status 1.

Reproduce this error by running:
==> cd /home/parallels/capstone/workspace/build_isolated/osqp && /home/parallels/capstone/workspace/devel_isolated/laikago_description/env.sh cmake /home/parallels/capstone/workspace/src/osqp -DCMAKE_INSTALL_PREFIX=/home/parallels/capstone/workspace/devel_isolated/osqp -G 'Unix Makefiles'

Command failed, exiting.
```

**Comment by JulienRineau** [comment]
Thank you @traversaro!
I still I'm a still missing something unfortunately. To be sure there is no issues due to my previous work I created a separated workspace. Here is what I've done
```
mkdir test_ws
cd test_ws
mkdir src
catkin_make
```
Move [a1_cpp](https://github.com/ShuoYangRobotics/A1-QP-MPC-Controller/tree/main/src/a1_cpp) in src
```
cd src
git clone https://github.com/ori-drs/osqp.git --recursive
git clone https://github.com/robotology/osqp-eigen.git --recursive
cd ..
catkin_make_isolated
```

Here is what I obtain
```
parallels@ubuntu-linux-20-04-desktop:~/capstone/test_ws$ catkin_make_isolated
Base path: /home/parallels/capstone/test_ws
Source space: /home/parallels/capstone/test_ws/src
Build space: /home/parallels/capstone/test_ws/build_isolated
Devel space: /home/parallels/capstone/test_ws/devel_isolated
Install space: /home/parallels/capstone/test_ws/install_isolated
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~  traversing 3 packages in topological order:
~~  - a1_cpp
~~  - osqp (plain cmake)
~~  - osqp-eigen (plain cmake)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The packages or cmake arguments have changed, forcing cmake invocation

==> Processing catkin package: 'a1_cpp'
==> Creating build directory: 'build_isolated/a1_cpp'
==> cmake /home/parallels/capstone/test_ws/src/a1_cpp -DCATKIN_DEVEL_PREFIX=/home/parallels/capstone/test_ws/devel_isolated/a1_cpp -DCMAKE_INSTALL_PREFIX=/home/parallels/capstone/test_ws/install_isolated -G Unix Makefiles in '/home/parallels/capstone/test_ws/build_isolated/a1_cpp'
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_PREFIX_PATH: 
-- Using CATKIN_DEVEL_PREFIX: /home/parallels/capstone/test_ws/devel_isolated/a1_cpp
-- Using CMAKE_PREFIX_PATH: /home/parallels/capstone/workspace/devel;/home/parallels/CS206_final/workspace/devel;/home/parallels/catkin_ws/devel;/opt/ros/noetic
-- This workspace overlays: /home/parallels/capstone/workspace/devel;/home/parallels/CS206_final/workspace/devel;/home/parallels/catkin_ws/devel;/opt/ros/noetic
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python3
-- Using Debian Python package layout
-- Found PY_em: /usr/lib/python3/dist-packages/em.py  
-- Using empy: /usr/lib/python3/dist-packages/em.py
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/parallels/capstone/test_ws/build_isolated/a1_cpp/test_results
-- Forcing gtest/gmock from source, though one was otherwise available.
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Found PythonInterp: /usr/bin/python3 (found version "3.8.10") 
-- Found Threads: TRUE  
-- Using Python nosetests: /usr/bin/nosetests3
-- catkin 0.8.10
-- BUILD_SHARED_LIBS is on
CMake Error at CMakeLists.txt:39 (find_package):
  By not providing "FindOsqpEigen.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "OsqpEigen", but CMake did not find one.

  Could not find a package configuration file provided by "OsqpEigen" with
  any of the following names:

    OsqpEigenConfig.cmake
    osqpeigen-config.cmake

  Add the installation prefix of "OsqpEigen" to CMAKE_PREFIX_PATH or set
  "OsqpEigen_DIR" to a directory containing one of the above files.  If
  "OsqpEigen" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/home/parallels/capstone/test_ws/build_isolated/a1_cpp/CMakeFiles/CMakeOutput.log".
See also "/home/parallels/capstone/test_ws/build_isolated/a1_cpp/CMakeFiles/CMakeError.log".
<== Failed to process package 'a1_cpp': 
  Command '['cmake', '/home/parallels/capstone/test_ws/src/a1_cpp', '-DCATKIN_DEVEL_PREFIX=/home/parallels/capstone/test_ws/devel_isolated/a1_cpp', '-DCMAKE_INSTALL_PREFIX=/home/parallels/capstone/test_ws/install_isolated', '-G', 'Unix Makefiles']' returned non-zero exit status 1.

Reproduce this error by running:
==> cd /home/parallels/capstone/test_ws/build_isolated/a1_cpp && cmake /home/parallels/capstone/test_ws/src/a1_cpp -DCATKIN_DEVEL_PREFIX=/home/parallels/capstone/test_ws/devel_isolated/a1_cpp -DCMAKE_INSTALL_PREFIX=/home/parallels/capstone/test_ws/install_isolated -G 'Unix Makefiles'

Command failed, exiting.
```
I can't find the two files **_OsqpEigenConfig.cmake_** and **_osqpeigen-config.cmake_**

Am I doing something wrong ?

**Comment by S-Dafarra** [comment]
At this point, I think it is an issue of ``a1_cpp`` that does not specify ``osqp-eigen`` as dependency: https://github.com/ShuoYangRobotics/A1-QP-MPC-Controller/blob/de07f355b93bee95151296d814fc47d3c1fb8349/src/a1_cpp/package.xml#L42-L50

**Comment by wxmerkt** [comment]
@JulienRineau I have a fork with the fixes needed to compile it here: https://github.com/wxmerkt/A1-QP-MPC-Controller

Note that we also use a different `unitree_legged_sdk`, but I didn't test that here. But the OsqpEigen code is fixed in the above repository

**Comment by JulienRineau** [comment]
Awesome. I still have issues with the [a1_cpp](https://github.com/ShuoYangRobotics/A1-QP-MPC-Controller/tree/main/src/a1_cpp) repo but everything concerning osqp-eigen has been solved. 

I'll close this issue then.

Thank you @wxmerkt @S-Dafarra and @traversaro for your help

**Comment by JulienRineau** [comment]
Hey @wxmerkt I have switch to docker and use your forked version of A1-QP-MPC because even by including unitree_legged_sdk in the catkin workspace it did not worked. However when I try to `docker build -t a1_unitree_gazebo_image .`
I obtain this:
```
(meng) bike@bike:~/Documents/meng/A1-QP-MPC-Controller/gazebo_docker$ docker build -t a1_unitree_gazebo_image .
Sending build context to Docker daemon  7.168kB
Step 1/44 : FROM osrf/ros:melodic-desktop-full
 ---> 490a8fac9e16
Step 2/44 : LABEL maintainer="shuoyang@andrew.cmu.edu"
 ---> Using cache
 ---> 54b2d4888795
Step 3/44 : ENV REFRESH_AT 2022-03-22
 ---> Using cache
 ---> 2085865d58c9
Step 4/44 : ENV NVIDIA_VISIBLE_DEVICES     ${NVIDIA_VISIBLE_DEVICES:-all}
 ---> Using cache
 ---> 4142b5cab356
Step 5/44 : ENV NVIDIA_DRIVER_CAPABILITIES     ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}graphics
 ---> Using cache
 ---> 01ad7398ae2f
Step 6/44 : RUN   if [ "x$(nproc)" = "x1" ] ; then export USE_PROC=1 ;       else export USE_PROC=$(($(nproc)/2)) ; fi &&       apt-get update && apt-get install -y       vim       libatlas-base-dev       libeigen3-dev       libgoogle-glog-dev       libsuitesparse-dev       python-catkin-tools       python3-matplotlib       gfortran       autoconf       coinor-libipopt-dev       libgfortran3       curl       libopenmpi-dev       apt-utils       software-properties-common       build-essential       libssl-dev       wget       libtool       cmake
 ---> Running in 8ba808a22298
Get:1 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:2 http://packages.ros.org/ros/ubuntu bionic InRelease [4680 B]
Get:3 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:4 http://packages.ros.org/ros/ubuntu bionic/main amd64 Packages [796 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [83.3 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:8 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:10 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Reading package lists...
E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease is not valid yet (invalid for another 7h 8min 18s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease is not valid yet (invalid for another 7h 10min 12s). Updates for this repository will not be applied.
E: Release file for http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease is not valid yet (invalid for another 7h 6min 44s). Updates for this repository will not be applied.

```
Did you ever had this issue ?

**Comment by JulienRineau** [comment]
Thanks a lot @wxmerkt. I take the liberty of asking more questions about this repo here because the issue is already closed. I ran your repo with Docker because it seems easier. However when trying to run the simulation with 
`sudo roslaunch unitree_gazebo normal.launch rname:=a1 wname:=stairs_single ` 
I obtain
`[gazebo_gui-3] process has died`
And the log is:
`cat: /root/.ros/log/a8a1848a-76b4-11ed-bad4-a8a1596e44b4/gazebo_gui-3.log: Permission denied`

This seems to be an issue related to launching a GUI with docker hower the repo implemented all the requirements I found (e.g https://wiki.ros.org/docker/Tutorials/GUI)

Did you ever had this problem ?

**Comment by wxmerkt** [comment]
Hi @JulienRineau 
I haven't run the code in the repository or looked into it too deeply so cannot comment in too much detail. One reason this issue could happen is if your uid/gid inside the Docker is not the same as your username outside e.g. if you want to give access to the xhost. You can manually set the uid/gid of the user inside docker when building the image to equal the one of your user outside if that was the issue. But that may only be one cause of failure.
Second, and this is only an observation, I am not sure why you need `sudo` for roslaunch. I am aware that Unitree in some cases does some unorthodox memory blocking/allocation that requires sudo (e.g. on the robot and for controlling robots rather than managing permissions more explicitly), but not sure why that would be the case here for Gazebo. Again, I haven't run or analysed the code in the linked repositories too closely, with my related experience only stemming from running experiments on the physical robot and packaging/build system fixes for the related libraries including Unitree's SDK
